StartupEvents.registry('item', event => {
    event.create('mana_lead_dust').displayName('Mana Infused Lead Dust')
    event.create('mana_iron_dust').displayName('Mana Infused Iron Dust')
    event.create('mana_gold_dust').displayName('Mana Infused Gold Dust')
    event.create('mana_copper_dust').displayName('Mana Infused Copper Dust')
    event.create('mana_nickel_dust').displayName('Mana Infused Nickel Dust')
    event.create('imbued_lead_dust').displayName('Mana Imbued Lead Dust')
    event.create('imbued_iron_dust').displayName('Mana Imbued Iron Dust')
    event.create('imbued_gold_dust').displayName('Mana Imbued Gold Dust')
    event.create('imbued_copper_dust').displayName('Mana Imbued Copper Dust')
    event.create('imbued_nickel_dust').displayName('Mana Imbued Nickel Dust')
    event.create('pure_lead_dust').displayName('Pure Mana Imbued Lead Dust')
    event.create('pure_iron_dust').displayName('Pure Mana Imbued Iron Dust')
    event.create('pure_gold_dust').displayName('Pure Mana Imbued Gold Dust')
    event.create('pure_copper_dust').displayName('Pure Mana Imbued Copper Dust')
    event.create('pure_nickel_dust').displayName('Pure Mana Imbued Nickel Dust')
    event.create('elven_lead_dust').displayName('Elven Imbued Lead Dust')
    event.create('elven_iron_dust').displayName('Elven Imbued Iron Dust')
    event.create('elven_gold_dust').displayName('Elven Imbued Gold Dust')
    event.create('elven_copper_dust').displayName('Elven Imbued Copper Dust')
    event.create('elven_nickel_dust').displayName('Elven Imbued Nickel Dust')
    event.create('soul_lead_dust').displayName('Elven Spirited Lead Dust')
    event.create('soul_iron_dust').displayName('Elven Spirited Iron Dust')
    event.create('soul_gold_dust').displayName('Elven Spirited Gold Dust')
    event.create('soul_copper_dust').displayName('Elven Spirited Copper Dust')
    event.create('soul_nickel_dust').displayName('Elven Spirited Nickel Dust')
    event.create('blood_lead_dust').displayName('Blood Spirited Lead Dust')
    event.create('blood_iron_dust').displayName('Blood Spirited Iron Dust')
    event.create('blood_gold_dust').displayName('Blood Spirited Gold Dust')
    event.create('blood_copper_dust').displayName('Blood Spirited Copper Dust')
    event.create('blood_nickel_dust').displayName('Blood Spirited Nickel Dust')
})