StartupEvents.registry("fluid", event => {
	event.create('soul_fluid')
	.displayName('Soul Fluid')
	.thickTexture(0xFFFFFF)
	.bucketColor(0xFFFFFF)
	event.create('refined_fuel')
	.displayName('Refined Fuel')
	.thickTexture(0xFFD580)
	.bucketColor(0xFFD580)
	event.create('creosote')
	.displayName('Creosote Oil')
	.thickTexture(0x5C4033)
	.bucketColor(0x5C4033)
	event.create('tree_oil') 	
	.displayName('Tree Oil')
	.thickTexture(0x8B8000)
	.bucketColor(0x8B8000)

})