// priority: 0


StartupEvents.registry('item', event => {
	//Assets are slightly changed versions of botania, ars nouveau and storage drawers items (Manasteel ingot and nugget, starbuncle shards, tablets and upgrade templatee)
	//Many assets are retextured from Applied Energistics 2
	event.create('manaelectrum_ingot').displayName('Manaelectrum Ingot')
	event.create('manaelectrum_nugget').displayName('Manaelectrum Nugget')
	event.create('mana_gem').displayName('Mana Gem')
	event.create('tablet_base').displayName('Ritual Tablet Base')
	event.create('livingwood_storage').displayName('Livingwood Storage')
	event.create('rune_logic').displayName('Rune of Logic')
	event.create('rune_calculation').displayName('Rune of Calculation')
	event.create('rune_engineering').displayName('Rune of Engineering')
	event.create('nether_quartz_crystal').displayName('Nether Quartz Crystal')
	event.create('nether_quartz_dust').displayName('Nether Quartz Dust')
	event.create('soul_pearl').displayName('Soul Pearl')
	event.create('dense_copper_dust').glow(true).displayName('Dense Copper Manaparticle')
	event.create('dense_zinc_dust').glow(true).displayName('Dense Zinc Manaparticle')
	event.create('introsceptre').displayName('The Introsceptre')
	event.create('zinc_plate').displayName('Zinc Plate')
	event.create('zinc_gear').displayName('Zinc Gear')
	event.create('zinc_dust').displayName('Zinc Dust')
	event.create('brass_gear').displayName('Brass Gear')
	event.create('manasteel_gear').displayName('Manasteel Gear')
	event.create('clay_gear').displayName('Clay Gear')
	event.create('glow_rosin').displayName('Glow Rosin')
	event.create('hot_resin').displayName('Hot Resin')
	event.create('brass_crystal').displayName('Brass Crystal')
	event.create('brass_dust').displayName('Brass Dust')
	event.create('fiery_coal').displayName('Fiery Coal').burnTime(4800)
	event.create('vitric_diamond').displayName('Vitric Diamond')
	event.create('blood_drop').displayName('Drop of Blood')
	event.create('crystallised_blood').displayName('Crystallised Blood')
	event.create('runic_ingot').displayName('Runic Ingot')
	event.create('blooded_source').displayName('Blooded Source Gem')
	event.create('sap').displayName('Sap')
	event.create('ender_sap').displayName('Ender Sap')
	event.create('scorching_sulfur').displayName('Scorching Sulfur')
	event.create('source_timber').displayName('Source Timber')
	event.create('runic_flux_circuit').displayName('Runic Flux Circuit')
	event.create('terra_cable').displayName('Terra Cable')
	event.create('tin_wire').displayName('Tin Wire')
	event.create('pure_earth_essence').glow(true).displayName('Pure Earth Essence')
	event.create('pure_water_essence').glow(true).displayName('Pure Water Essence')
	event.create('pure_fire_essence').glow(true).displayName('Pure Fire Essence')
	event.create('pure_air_essence').glow(true).displayName('Pure Air Essence')
})
StartupEvents.registry('block', event => {
	event.create('fractured_obsidian')
	.material('stone')
	.displayName('Fractured Obsidian')
	event.create('bloodstone_block')
	.material('stone')
	.displayName('Bloodstone Block')
	event.create('crystalliser')
	.material('metal')
	.displayName('Manasteel Crystalliser')
	event.create('crusher')
	.material('metal')
	.displayName('Primitive Mana Crusher')
	event.create('runic_block')
	.material('metal')
	.displayName('Runic Block')
	event.create('infused_livingwood')
	.material('wood')
	.displayName('Infused Livingwood')
	event.create('dirty_dirt')
	.material('dirt')
	.displayName('Dirty Dirt')
	event.create('runic_catalyst')
	.material('stone')
	.displayName('Runic Catalyst')
	event.create('sulfur_ore')
	.material('nether_gold_ore')
	.displayName('Netherrack Sulfur Ore')
	event.create('compressed_alloy_block')
	.material('metal')
	.displayName('Compressed Manaconductive Block')
})


