// priority: 0
JEIEvents.information(event => {
    event.addItem('ae2:quartz_glass', ['§8General Information', 'Obtained by having lightning strike an area of sand which has the Certus Quartz Block item dropped ontop'])
    event.addItem('#botania:lens', ['§8General Information', 'Can be combined with any other lens by putting both lenses together in a crafting menu with a Honey Bottle or Slime Ball'])
	event.addItem('genericbotaniapacktweaker:dieselotus', ['§7Other Changes', 'Similar to the Thermalily; can burn refined fuel, creosote oil and tree oil for Mana in that order of level of mana produced'])
	event.addItem('twigs:bloodstone', ['§7Other Changes', 'Obtained by killing a mob ontop of stone, or can be found naturally in the Nether'])
	event.addItem('thermal:apatite', ['§8General Information', 'There is a rare chance of Apatite ore spawning from using an Orechid with Andesite'])
	event.addItem('ars_nouveau:imbuement_chamber', ['§8General Information', 'Source is not required for recipes, but does speed up the crafting process'])
	event.addItem('ars_nouveau:agronomic_sourcelink', ['§6KubeJS Changes', 'Mana Spreaders work on Source Jars, and can transfer Mana to Source, currently it is the only way to get Source!'])
	event.addItem('ars_nouveau:volcanic_sourcelink', ['§6KubeJS Changes', 'Mana Spreaders work on Source Jars, and can transfer Mana to Source, currently it is the only way to get Source!'])
	event.addItem('ars_nouveau:alchemical_sourcelink', ['§6KubeJS Changes', 'Mana Spreaders work on Source Jars, and can transfer Mana to Source, currently it is the only way to get Source!'])
	event.addItem('ars_nouveau:vitalic_sourcelink', ['§6KubeJS Changes', 'Mana Spreaders work on Source Jars, and can transfer Mana to Source, currently it is the only way to get Source!'])
	event.addItem('ars_nouveau:mycelial_sourcelink', ['§6KubeJS Changes', 'Mana Spreaders work on Source Jars, and can transfer Mana to Source, currently it is the only way to get Source!'])
	event.addItem('minecraft:nether_quartz_ore', ['§7Other Changes', 'No longer naturally generates in the Nether'])
	event.addItem('minecraft:quartz', ['§7Other Changes', 'Nether Quartz Ore no longer naturally generates in the Nether'])
	event.addItem('easy_mob_farm:desert_farm', ['§7Other Changes', 'Higher tiers of Mob Farms both decrease the time to generate new items, and increases the amount generated substantially'])
	event.addItem('easy_mob_farm:monster_plains_cave_farm', ['§7Other Changes', 'Higher tiers of Mob Farms both decrease the time to generate new items, and increases the amount generated substantially'])
	event.addItem('easy_mob_farm:swamp_farm', ['§7Other Changes', 'Higher tiers of Mob Farms both decrease the time to generate new items, and increases the amount generated substantially'])
	event.addItem('easy_mob_farm:creative_mob_farm', ['§7Other Changes', 'Higher tiers of Mob Farms both decrease the time to generate new items, and increases the amount generated substantially'])
	event.addItem('minecraft:piston', ['§1Quark Changes', 'Quark allows Pistons to move tile entities, such as chests'])
	event.addItem('minecraft:sticky_piston', ['§1Quark Changes', 'Quark allows Pistons to move tile entities, such as chests'])
	event.addItem('ae2:energy_cell', ['§6KubeJS Changes', 'Mana Spreaders work on Energy Cells, and can transfer Mana to AE Energy, A more concentrated, but malleable form of Mana!'])
	event.addItem('ae2:dense_energy_cell', ['§6KubeJS Changes', 'Mana Spreaders work on Energy Cells, and can transfer Mana to AE Energy, A more concentrated form of Mana!'])
	event.addItem('ars_nouveau:source_jar', ['§6KubeJS Changes', 'Mana Spreaders work on Source Jars, and can transfer Mana to Source, but it is not possible to transfer Source to Mana!'])
	event.addItem('farmersdelight:cabbage', ['§6KubeJS Changes', 'Seeds obtainable through a Mana Pool with an Alchemy Catalyst and seeds'])
	event.addItem('farmersdelight:tomato', ['§6KubeJS Changes', 'Seeds obtainable through a Mana Pool with an Alchemy Catalyst and seeds'])
	event.addItem('supplementaries:flax', ['§6KubeJS Changes', 'Seeds obtainle through Ars Nouveau Enchanting Apparatus'])
	event.addItem('minecraft:obsidian', ['§0Garden of Glass', 'Getting the obsidian for a portal may be slow, but there could be a small chance of finding ruined portals. Use a Silk-Touch Pickaxe to obtain regular obsidian '])
	event.addItem('kubejs:fractured_obsidian', ['§6KubeJS Changes', 'Too weak to craft with, but can be placed to be a suitable portal material. Use a Silk-Touch Pickaxe to obtain Regular Obsidian '])
	event.addItem('ae2:certus_quartz_crystal', ['§8General Information', 'Make Budding Certus Quartz!'])
    event.addItem('kubejs:mythril_ore', ['§6KubeJS Changes', 'Only obtainable in the End, spawns rarely in End Islands.'])
	event.addItem('ae2:cable_anchor', ['§8General Information', 'Facades can be made by placing 4 cable anchors around a block in a crafting table'])
	event.addItem('ars_nouveau:drygmy_shard', ['§8General Information', 'Press U on Summoning Altar in JEI to See Summoning Recipes for Ars Nouveau Mobs'])
	event.addItem('ars_nouveau:whirlisprig_shards', ['§8General Information', 'Press U on Summoning Altar in JEI to See Summoning Recipes for Ars Nouveau Mobs'])
	event.addItem('ars_nouveau:wixie_shards', ['§8General Information', 'Press U on Summoning Altar in JEI to See Summoning Recipes for Ars Nouveau Mobs'])
	event.addItem('ars_nouveau:starbuncle_shards', ['§8General Information', 'Press U on Summoning Altar in JEI to See Summoning Recipes for Ars Nouveau Mobs'])
    event.addItem('genericbotaniapacktweaker:creeper_gland', ['§6KubeJS Changes', 'Can be obtained by killing a creeper when it is near exploding. A Heisei Dream may be useful for this'])
	event.addItem('botania:ender_air_bottle', ['§6KubeJS Changes', 'Can be obtained by right clicking in the end with Glass Bottle or by right clicking on Ender Conduit with a Glass Bottle'])
})

ItemEvents.tooltip(event => {
	event.add('thermal:apatite', "§8There's a rare chance of Apatite ore spawning from using an Orechid with Andesite")
	event.add('kubejs:nether_quartz_dust', "§8This might be expensive...")
	event.add('kubejs:source_timber', "§8It tries to escape your grasp...")
    event.add('supplementaries:cog_block', "§8Only partially conscious")
	event.add('kubejs:runic_ingot', "§8Why would you make this?")
    event.add('botania:living_root', "§7Functions as bonemeal")
	event.add('botania:ender_air_bottle', '§8Can be obtained by right clicking in the end with a Glass Bottle or by right clicking on Ender Conduit with a Glass Bottle')
	event.add('ae2:controller', '§8A Mana-Energy System')
	event.add('ars_nouveau:drygmy_shard', '§9Press U on Summoning Altar in JEI to See Summoning Recipes for Ars Nouveau Mobs')
	event.add('ars_nouveau:whirlisprig_shards', '§9Press U on Summoning Altar in JEI to See Summoning Recipes for Ars Nouveau Mobs')
	event.add('ars_nouveau:wixie_shards', '§9Press U on Summoning Altar in JEI to See Summoning Recipes for Ars Nouveau Mobs')
	event.add('ars_nouveau:starbuncle_shards', '§9Press U on Summoning Altar in JEI to See Summoning Recipes for Ars Nouveau Mobs')
	event.add('ae2:logic_processor', '§7Why would you do that?')
	event.add('ae2:calculation_processor', '§7Why would you do that?')
	event.add('ae2:engineering_processor', '§7Why would you do that?')
	event.add('ae2:fluix_crystal', '§7An Ethical Experiment')
	event.add('kubejs:infused_livingwood', '§4A Work of Art')
	event.add('#quark:hollow_logs', '§7Shift next to one to crawl through')
	event.add('minecraft:glow_berries', '§7Good for your pet toretoise')
	event.add('create:zinc_ingot', '§7..What?')
	event.add('kubejs:dirty_dirt', '§7Gambling for Dirt')
	event.add('kubejs:runic_block', "Rubik's Cube")
	event.add('kubejs:blood_iron_dust', "§7Both superheated and regular heating will work, but superheating will give you more nuggets")
	event.add('kubejs:blood_gold_dust', "§7Both superheated and regular heating will work, but superheating will give you more nuggets")
	event.add('kubejs:blood_copper_dust', "§7Both superheated and regular heating will work, but superheating will give you more nuggets")
	event.add('kubejs:blood_nickel_dust', "§7Both superheated and regular heating will work, but superheating will give you more nuggets")
	event.add('kubejs:blood_lead_dust', "§7Both superheated and regular heating will work, but superheating will give you more nuggets")
})