
[types]

	[types.leaves_type]

		[types.leaves_type.ars_nouveau]
			blue_archwood = true
			green_archwood = true
			purple_archwood = true
			red_archwood = true

		[types.leaves_type.quark]
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			pink_blossom = true
			yellow_blossom = true
			red_blossom = true
			ancient = true

		[types.leaves_type.ars_elemental]
			yellow_archwood = true

		[types.leaves_type.colorfulazaleas]
			blue_azalea = true
			blue_blooming_azalea = true
			blue_flowering_azalea = true
			orange_azalea = true
			orange_blooming_azalea = true
			orange_flowering_azalea = true
			pink_azalea = true
			pink_blooming_azalea = true
			pink_flowering_azalea = true
			purple_azalea = true
			purple_blooming_azalea = true
			purple_flowering_azalea = true
			red_azalea = true
			red_blooming_azalea = true
			red_flowering_azalea = true
			white_azalea = true
			white_blooming_azalea = true
			white_flowering_azalea = true
			yellow_azalea = true
			yellow_blooming_azalea = true
			yellow_flowering_azalea = true

	[types.wood_type]

		[types.wood_type.ars_nouveau]
			archwood = true

		[types.wood_type.quark]
			bamboo = true
			azalea = true
			blossom = true
			ancient = true

		[types.wood_type.botania]
			livingwood = true
			dreamwood = true

		[types.wood_type.colorfulazaleas]
			tecal_azalea = true
			fiss_azalea = true
			roze_azalea = true
			azule_azalea = true
			bright_azalea = true
			walnut_azalea = true
			titanium_azalea = true

[entries]

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

		[entries.leaves_type.mcwfences]
			hedge = true

	[entries.wood_type]

		[entries.wood_type.mcwroofs]
			planks_upper_steep_roof = true
			top_roof = true
			lower_roof = true
			planks_roof = true
			upper_steep_roof = true
			steep_roof = true
			roof = true
			planks_attic_roof = true
			upper_lower_roof = true
			planks_top_roof = true
			planks_steep_roof = true
			attic_roof = true
			planks_upper_lower_roof = true
			planks_lower_roof = true

		[entries.wood_type.mcwwindows]
			plank_window = true
			louvered_shutter = true
			plank_window2 = true
			plank_four_window = true
			stripped_log_window2 = true
			log_parapet = true
			window2 = true
			stripped_log_four_window = true
			four_window = true
			blinds = true
			plank_parapet = true
			window = true
			shutter = true
			stripped_log_window = true

		[entries.wood_type.decorative_blocks]
			beam = true
			support = true
			seat = true
			palisade = true

		[entries.wood_type.mcwlights]
			soul_tiki_torch = true
			tiki_torch = true

		[entries.wood_type.mcwfences]
			highley_gate = true
			picket_fence = true
			horse_fence = true
			pyramid_gate = true
			stockade_fence = true
			wired_fence = true

		[entries.wood_type.create]
			window_pane = true
			window = true

		[entries.wood_type.storagedrawers]
			half_drawers_1 = true
			half_drawers_4 = true
			half_drawers_2 = true
			trim = true
			full_drawers_2 = true
			full_drawers_4 = true
			full_drawers_1 = true

		[entries.wood_type.quark]
			vertical_planks = true
			chest = true
			ladder = true
			post = true
			trapped_chest = true
			bookshelf = true
			stripped_post = true
			hollow_log = true

		[entries.wood_type.mcwpaths]
			planks_path = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.twigs]
			table = true

